spring.application.name=chatting4ever-server

# Database H2
spring.datasource.url=jdbc:h2:file:./chatting4ever-server/src/main/resources/data/chatdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Console H2 esplicita
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# SECURITY
spring.security.user.name=sa

# EMAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=chatting4ever.app@gmail.com
spring.mail.password=njvf uuio dpsc atlp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true